title: MYTHAXIS MAGAZINE

# To make .html URL's and relative links to avoid baseURL
uglyurls: true
relativeurls: true
canonifyURLs: true
languageCode: en-us
theme: massively
publishDir: docs
googleanalytics: 'UA-146012578-1'
disqusShortname: ''
disableKinds:
  - RSS
languages:
  en:
    languageName: English
staticDir:
- static
- static-xway


taxonomies:
  category: categories
  issue: issues
  tag: tags
  author: authors


params:
  posts:
    pageSize: '50'
    featuredPost: true
    paginationPages: 2
    showFirstLast: false
  description: Mythaxis Magazine, Speculative Fiction Without Distraction
  keywords: Mythaxis Magazine Science Fiction and Fantasy Modern Fiction
  # The slug/name of the current section. This is used to theme pages
  # which are not in a specific section (homepage, about, etc.)
  currentIssue: Issue 24


menu:
  main:
    - name: Home
      url: /
      weight: -10
      # ####
      # layouts/nav.html injects section specific menu items here
      # ####
    - name: Archive
      url: /archive.html
      weight: -7
    - name: 2021 Submissions
      url: /submissions.html
      weight: -6
    - name: Contact
      url: /about.html
      weight: -5
